export enum TokenType {
  EOF = 'EOF',
  Identifier = 'Identifier',
  Number = 'Number',
  Plus = '+',
  Minus = '-',
  Star = '*',
  Slash = '/',
  Assign = '=',
  Equal = '==',
  NotEqual = '!=',
  LessThan = '<',
  GreaterThan = '>',
  LeftParen = '(',
  RightParen = ')',
  Semicolon = ';',
  Comma = ',',
  Let = 'let',
  Const = 'const',
  If = 'if',
  Else = 'else',
  Return = 'return',
  Function = 'function',
  Unknown = 'Unknown',
}
